/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"github.com/idevz/kwm/pkg"
	"time"

	v1 "github.com/idevz/kwm/pkg/apis/kubeweibomesh/v1"
	"github.com/idevz/kwm/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"
)

// WeibMeshesGetter has a method to return a WeibMeshInterface.
// A group's client should implement this interface.
type WeibMeshesGetter interface {
	WeibMeshes(namespace string) WeibMeshInterface
}

// WeibMeshInterface has methods to work with WeibMesh resources.
type WeibMeshInterface interface {
	Create(*v1.WeibMesh) (*v1.WeibMesh, error)
	Update(*v1.WeibMesh) (*v1.WeibMesh, error)
	UpdateStatus(*v1.WeibMesh) (*v1.WeibMesh, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.WeibMesh, error)
	List(opts metav1.ListOptions) (*v1.WeibMeshList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.WeibMesh, err error)
	pkg.WeibMeshExpansion
}

// weibMeshes implements WeibMeshInterface
type weibMeshes struct {
	client rest.Interface
	ns     string
}

// newWeibMeshes returns a WeibMeshes
func newWeibMeshes(c *pkg.WeibomeshV1Client, namespace string) *weibMeshes {
	return &weibMeshes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the weibMesh, and returns the corresponding weibMesh object, and an error if there is any.
func (c *weibMeshes) Get(name string, options metav1.GetOptions) (result *v1.WeibMesh, err error) {
	result = &v1.WeibMesh{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("weibmeshes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WeibMeshes that match those selectors.
func (c *weibMeshes) List(opts metav1.ListOptions) (result *v1.WeibMeshList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.WeibMeshList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("weibmeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested weibMeshes.
func (c *weibMeshes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("weibmeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a weibMesh and creates it.  Returns the server's representation of the weibMesh, and an error, if there is any.
func (c *weibMeshes) Create(weibMesh *v1.WeibMesh) (result *v1.WeibMesh, err error) {
	result = &v1.WeibMesh{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("weibmeshes").
		Body(weibMesh).
		Do().
		Into(result)
	return
}

// Update takes the representation of a weibMesh and updates it. Returns the server's representation of the weibMesh, and an error, if there is any.
func (c *weibMeshes) Update(weibMesh *v1.WeibMesh) (result *v1.WeibMesh, err error) {
	result = &v1.WeibMesh{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("weibmeshes").
		Name(weibMesh.Name).
		Body(weibMesh).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *weibMeshes) UpdateStatus(weibMesh *v1.WeibMesh) (result *v1.WeibMesh, err error) {
	result = &v1.WeibMesh{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("weibmeshes").
		Name(weibMesh.Name).
		SubResource("status").
		Body(weibMesh).
		Do().
		Into(result)
	return
}

// Delete takes name of the weibMesh and deletes it. Returns an error if one occurs.
func (c *weibMeshes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("weibmeshes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *weibMeshes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("weibmeshes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched weibMesh.
func (c *weibMeshes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.WeibMesh, err error) {
	result = &v1.WeibMesh{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("weibmeshes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
