/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"github.com/idevz/kwm/pkg"
	kubeweibomeshv1 "github.com/idevz/kwm/pkg/apis/kubeweibomesh/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/testing"
)

// FakeWeibMeshes implements WeibMeshInterface
type FakeWeibMeshes struct {
	Fake *pkg.FakeWeibomeshV1
	ns   string
}

var weibmeshesResource = schema.GroupVersionResource{Group: "weibomesh.weibo.com", Version: "v1", Resource: "weibmeshes"}

var weibmeshesKind = schema.GroupVersionKind{Group: "weibomesh.weibo.com", Version: "v1", Kind: "WeibMesh"}

// Get takes name of the weibMesh, and returns the corresponding weibMesh object, and an error if there is any.
func (c *FakeWeibMeshes) Get(name string, options v1.GetOptions) (result *kubeweibomeshv1.WeibMesh, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(weibmeshesResource, c.ns, name), &kubeweibomeshv1.WeibMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubeweibomeshv1.WeibMesh), err
}

// List takes label and field selectors, and returns the list of WeibMeshes that match those selectors.
func (c *FakeWeibMeshes) List(opts v1.ListOptions) (result *kubeweibomeshv1.WeibMeshList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(weibmeshesResource, weibmeshesKind, c.ns, opts), &kubeweibomeshv1.WeibMeshList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kubeweibomeshv1.WeibMeshList{ListMeta: obj.(*kubeweibomeshv1.WeibMeshList).ListMeta}
	for _, item := range obj.(*kubeweibomeshv1.WeibMeshList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested weibMeshes.
func (c *FakeWeibMeshes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(weibmeshesResource, c.ns, opts))

}

// Create takes the representation of a weibMesh and creates it.  Returns the server's representation of the weibMesh, and an error, if there is any.
func (c *FakeWeibMeshes) Create(weibMesh *kubeweibomeshv1.WeibMesh) (result *kubeweibomeshv1.WeibMesh, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(weibmeshesResource, c.ns, weibMesh), &kubeweibomeshv1.WeibMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubeweibomeshv1.WeibMesh), err
}

// Update takes the representation of a weibMesh and updates it. Returns the server's representation of the weibMesh, and an error, if there is any.
func (c *FakeWeibMeshes) Update(weibMesh *kubeweibomeshv1.WeibMesh) (result *kubeweibomeshv1.WeibMesh, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(weibmeshesResource, c.ns, weibMesh), &kubeweibomeshv1.WeibMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubeweibomeshv1.WeibMesh), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWeibMeshes) UpdateStatus(weibMesh *kubeweibomeshv1.WeibMesh) (*kubeweibomeshv1.WeibMesh, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(weibmeshesResource, "status", c.ns, weibMesh), &kubeweibomeshv1.WeibMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubeweibomeshv1.WeibMesh), err
}

// Delete takes name of the weibMesh and deletes it. Returns an error if one occurs.
func (c *FakeWeibMeshes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(weibmeshesResource, c.ns, name), &kubeweibomeshv1.WeibMesh{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWeibMeshes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(weibmeshesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &kubeweibomeshv1.WeibMeshList{})
	return err
}

// Patch applies the patch and returns the patched weibMesh.
func (c *FakeWeibMeshes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *kubeweibomeshv1.WeibMesh, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(weibmeshesResource, c.ns, name, pt, data, subresources...), &kubeweibomeshv1.WeibMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubeweibomeshv1.WeibMesh), err
}
